version: "3.7"

services:
  api-gateway:
  # nginx를 image로 다운로드
    image: nginx:latest
    volumes: # default.conf 경로
      - ./api-gateway/default.conf:/etc/nginx/conf.d/default.conf
    ports: # nginx의 기본포트
      - 80:80

  auth-service:
    build:
      context: ./services/auth
      dockerfile: Dockerfile
    volumes:
      - ./services/auth/src:/auth-service/src

  stock-service:
    build:
      context: ./services/stock
      dockerfile: Dockerfile